name: Build, Test, and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Full Repository History
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full Git history so git diff works correctly

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Compile the Java Code
      - name: Compile Java Code with Maven
        run: mvn clean compile

      # 4. Verify Compiled Classes
      - name: Verify Compiled Classes
        run: |
          echo "Listing compiled classes in target/classes:"
          ls -R target/classes

      # 5. Identify Modified Java Files
      - name: Identify Modified Java Files
        id: changes
        run: |
          # Find all modified .java files in the latest commit
          modified_files=$(git diff --name-only HEAD^ HEAD | grep -E '\.java$' || true)
          echo "Identified modified files: $modified_files"
          echo "modified_files=$modified_files" >> $GITHUB_ENV

      # 6. Generate Unit Tests with EvoSuite
      - name: Generate Unit Tests with EvoSuite
        if: ${{ env.modified_files != '' }}
        run: |
          echo "Modified files: $modified_files"
          mkdir -p evosuite-tests
          for file in $modified_files; do
            class_name=$(basename $file .java)
            package=$(dirname $file | sed -e 's/\//./g')
            echo "Processing ${package}.${class_name}"
            java -jar path/to/evosuite.jar \
              -generateTests \
              -class ${package}.${class_name} \
              -projectCP target/classes \
              -Dtest_dir=evosuite-tests \
              -Dtest_for_getters_setters=true || echo "EvoSuite failed for ${package}.${class_name}"
          done
          echo "Generated tests directory contents:"
          ls -R evosuite-tests

      # 7. Warning if No Files Were Modified
      - name: Skip Workflow Warning
        if: ${{ env.modified_files == '' }}
        run: |
          echo "No Java files were modified in the last commit. Skipping EvoSuite test generation."

      # 8. Verify Tests by Running Them with Maven
      - name: Verify Tests
        if: ${{ env.modified_files != '' }}
        run: mvn test

      # 9. Commit and Push Generated Tests
      - name: Commit and Push Tests
        if: ${{ env.modified_files != '' }}
        run: |
          cp -r evosuite-tests/* src/test/java/
          echo "Files copied to src/test/java:"
          ls -R src/test/java
          
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git add src/test/java/
          git commit -m "Add EvoSuite generated unit tests" || echo "No changes to commit"
          git push origin main || echo "Failed to push changes"