name: Generate and Commit Unit Tests with GitHub Copilot AI

on:
  push:
    branches:
      - main

jobs:
  generate-unit-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for git diff

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Install Copilot CLI
      - name: Install GitHub Copilot CLI
        run: |
          npm install githubnext/copilot-cli

      # 4. Authenticate Copilot CLI
      - name: Authenticate Copilot CLI
        run: |
          copilot auth login --github-token "${{ secrets.GITHUB_TOKEN }}"

      # 5. Identify Modified Java Files
      - name: Identify Modified Java Files
        id: changes
        run: |
          modified_files=$(git diff --name-only HEAD^ HEAD | grep -E '\.java$' || true)
          echo "Identified modified files: $modified_files"
          echo "modified_files=$modified_files" >> $GITHUB_ENV

      # 6. Generate Unit Tests using GitHub Copilot AI
      - name: Generate Unit Tests using Copilot AI
        if: ${{ env.modified_files != '' }}
        run: |
          mkdir -p generated-tests  # Create folder to store generated tests
          echo "Processing modified files: $modified_files"
          
          for file in $modified_files; do
            # Extract the class name and identify the corresponding test file
            class_name=$(basename "$file" .java)
            test_file="generated-tests/${class_name}Test.java"

            # Call Copilot CLI to generate the test for the class
            copilot generate "$file" > "$test_file" || echo "Failed to generate test for $class_name"

            echo "Test generated for class $class_name at $test_file"
          done

          echo "Generated tests directory contents:"
          ls -R generated-tests

      # 7. Verify Generated Tests (Optional)
      - name: Verify Generated Tests
        if: ${{ env.modified_files != '' }}
        run: |
          mkdir -p src/test/java/
          mv generated-tests/* src/test/java/  # Move tests into the src/test/java/ directory
          mvn test

      # 8. Commit and Push Generated Tests
      - name: Commit and Push Tests
        if: ${{ env.modified_files != '' }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          
          git add src/test/java/
          git commit -m "Automatically generated unit tests for modified files" || echo "No changes to commit"
          git push origin main || echo "Push failed"